#!/usr/bin/env bash

MUTE=$(amixer get Master | grep -E -o -m 1 "\[\w*\]" | grep -o "\w*")
if [[ "$MUTE" = "off" ]] ; then
    volume=
    label=""
else
    volume=$(amixer get Master | grep -E -o -m 1 "[[:digit:]]*%" | grep -o "[[:digit:]]*")
    if (( $volume = 0)) ; then
        label=""
    else if (( $volume < 50)) ; then
        label=""
    else
        label=""
        fi
    fi
    volume="$volume%"
fi

echo "$label $volume"